# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200803_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiki',
            name='depth',
            field=models.IntegerField(default=1, verbose_name='深度'),
        ),
    ]
