# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-04 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_wiki_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bucket',
            field=models.CharField(default='', max_length=128, verbose_name='COS桶'),
        ),
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.CharField(default='', max_length=32, verbose_name='COS区域'),
        ),
    ]
