# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_filerepository'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='字节', null=True, verbose_name='文件大小'),
        ),
        migrations.AlterField(
            model_name='filerepository',
            name='key',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='文件存储在COS中名称'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='per_file_size',
            field=models.PositiveIntegerField(help_text='MB', verbose_name='单文件大小'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_space',
            field=models.PositiveIntegerField(help_text='MB', verbose_name='单项目空间'),
        ),
    ]
