# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-08-29 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_projectinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(1, '文件'), (2, '文件夹')], verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='project_member',
            field=models.PositiveIntegerField(verbose_name='单个项目成员数'),
        ),
    ]
