# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-28 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20200829_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerepository',
            name='file_type',
            field=models.SmallIntegerField(choices=[(2, '文件夹'), (1, '文件')], verbose_name='类型'),
        ),
    ]
